models/contact.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):     #contructor to inicialize the class Contact
        self.fullname = fullname    
        self.email = email
        self.phone = phone

app.py
from flask import Flask  # Incial config.
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from utils.db import db
from flask_migrate import Migrate
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = "secret key"
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

#db = SQLAlchemy()
db.init_app(app)
migrate = Migrate(app, db)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint("contacts", __name__)


@contacts.route("/")
def index():
    contacts = Contact.query.all()
    return render_template("index.html", contacts = contacts)


@contacts.route("/new", methods=['POST'])
def add_contact():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()

    flash('Contact added successfully')

    return redirect (url_for('contacts.index'))


@contacts.route("/update/<id>" , methods=['POST', 'GET'])
def update(id):
    contact = Contact.query.get(id)

    if request.method == 'POST':
        contact.fullname = request.form["fullname"]
        contact.email = request.form["email"]
        contact.phone = request.form["phone"]
        
        db.session.commit()

        flash('Contact updated successfully')

        return redirect(url_for("contacts.index"))

    else:    
        return render_template("update.html" , contact = contact)


@contacts.route("/delete/<id>")
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()

    flash('Contact deleted successfully')

    return redirect (url_for('contacts.index'))


@contacts.route("/about")
def about():
    return render_template("about.html")

templates/about.html
{% extends 'layout.html'%}

{% block body %}

<div class="text-light">
    <h1>About</h1>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nam reprehenderit dolores quas, placeat ad doloribus
        velit, dolor obcaecati a labore totam hic recusandae deserunt! Unde qui eum, incidunt, eaque nostrum illo sit error
        repellendus reprehenderit ullam doloremque voluptatum placeat delectus! Soluta in quae voluptates? Asperiores
        tempore aspernatur illum fuga aliquid incidunt architecto vitae doloribus dolorum, voluptas rem recusandae
        voluptatibus, nostrum optio, inventore nesciunt hic sint eum reiciendis maiores et. Asperiores accusamus cum
        necessitatibus aspernatur quos aliquam laudantium error amet illum ratione totam, eaque fuga ullam voluptatibus non
        eum! Possimus fuga porro accusamus, sapiente voluptate inventore, veniam, deleniti consequuntur adipisci consectetur
        veritatis optio quibusdam! Temporibus eius nisi accusantium reprehenderit quibusdam esse doloremque, ipsam dicta
        animi possimus veniam sunt commodi natus! Hic labore, animi at voluptate temporibus laudantium a provident fugit
        assumenda, debitis quod eum soluta, veniam quae obcaecati dignissimos? Veritatis rem facilis repellendus, quis
        quibusdam enim vero repellat, laborum ea minima tempore dicta sint laudantium aliquid cupiditate sunt eaque ut?
        Voluptate, modi libero nobis, eaque ea facilis necessitatibus quia, soluta reprehenderit adipisci saepe vel tempora
        repellat commodi! Enim deleniti libero, corporis neque quae porro doloremque sit saepe sequi quam quia dolore
        consectetur ipsa minima sed! Itaque harum aspernatur repellendus laborum quod voluptatem amet blanditiis eaque
        labore ipsam ratione odit quae, doloremque ducimus, vitae, ut nisi. Accusantium praesentium harum libero iure quos?
        Eveniet sint illum nihil repellat corporis odit obcaecati molestias sequi suscipit nulla praesentium vel provident
        quis perferendis tenetur quisquam quaerat earum, iure eos velit assumenda minima vero, deserunt quas? Labore totam
        reiciendis, numquam quos iste dolores nobis libero, commodi quisquam maxime repudiandae, dolorem obcaecati?
        Distinctio libero maxime doloribus officia eos commodi, provident impedit quis ipsa ab blanditiis eius nobis enim
        qui, quasi temporibus voluptatem. Atque aliquam ad animi, tempore quibusdam a amet nulla eum ipsa deserunt expedita
        molestias aperiam.
    </p>
</div>


{% endblock %}

templates/index.html
<!-- To heredit layout.html -->
{% extends 'layout.html' %} 


{% block body %}


    <div class="row">
        <div class="col-md-3">

            {% include 'partials/_message.html'%}

            {% include 'partials/_contactForm.html' %}

        </div>

        <div class="col-md-3">
            <div class="badge text-bg-primary text-wrap" style="width: 10rem; --bs-badge-padding-y: 0.5em; --bs-badge-font-size: 0.9em;">
                Para hacer
            </div>
                {% for contact in contacts %}
        
                    <div class="card mb-1 text-white bg-dark">

                        <div class="card-body">

                            <div class="d-flex justify-content-between">
                                <h5>{{contact.fullname}}</h5>
                                
                                <div>
                                    <!-- To move to function in contacts -->
                                    <a href="{{ url_for('contacts.update', id=contact.id) }}" class="btn bg-black text-white btn-sm rounded-1">Update</a> 
                                    <a href="{{ url_for('contacts.delete', id=contact.id) }}" class="btn btn-danger btn-sm rounded-1">Delete</a>
                                </div>

                            </div>

                            <p>{{contact.email}}</p>
                            <p>{{contact.phone}}</p>
                        </div>

                    </div>
        
                {% endfor %}


        </div>

        <div class="col-md-3">
            <div class="badge text-wrap"  style="width: 10rem; background-color:rgb(225, 225, 25); --bs-badge-padding-y: 0.5em;--bs-badge-font-size: 0.9em">
                En proceso
            </div>

            <div class="card mb-1 text-white bg-dark text-center">
                <h1>Holaaaaa</h1>
            </div>
        </div>

        <div class="col-md-3">
            <div class="badge text-wrap" style="width: 10rem; background-color:greenyellow; --bs-badge-padding-y: 0.5em;--bs-badge-font-size: 0.9em;">
                Terminado
            </div>

            <div class="card mb-1 text-white bg-dark text-center">
                <h1>Holaaaaa</h1>
            </div>
        </div>

    </div>



{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ScrumHub | App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
</head>
</head>
<body>
    
    {% include ('partials/_navbar.html')%}

    <div class="container p-2">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</body>
</html>

templates/partials/_contactForm.html
<form action="/new" method="post" class="card bg-dark form-grid text-light">

    <div class="card-body p-4">
        
        <div class="mb-3">
            <label for="fullname">Write your fullname</label>
            <input 
            type="text" 
            name="fullname" 
            placeholder="Write your fullname" 
            class="form-control rounded-0 bg-dark border-0 text-white">
        </div>
        
        <div class="mb-3">
            <label for="email">Write your email</label>
            <input 
            type="text" 
            name="email" 
            placeholder="Write your email" 
            class="form-control rounded-0 bg-dark border-0 text-white">
        </div>

        <div class="mb-3">
            <label for="phone">Write your phone</label>
            <input 
            type="text" 
            name="phone" 
            placeholder="Write your phone" 
            class="form-control rounded-0 bg-dark border-0 text-white">
        </div>
        
        <div class="d-grid gap-2">
            <button class="btn btn-primary">Save</button>
        </div>
    </div>

</form>

templates/partials/_message.html
{% with messages = get_flashed_messages() %}

{% if messages %}

    {% for message in messages %}

    <!-- <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check-circle-fill" viewBox="2 -2 25 25">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
    </svg>
    
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <div>
          {{ message }}
        </div>
    </div> -->

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    
    {% endfor %}

{% endif %}

{% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-dark ">
    <div class="container">
      <a class="navbar-brand text-light" href="/">ScrumHub</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item ">
            <a class="nav-link text-light" href="/about">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/update.html
{% extends 'layout.html' %}

{% block body %}

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form action="/update/{{contact.id}}" method="post" class="card bg-dark text-white">

            <div class="card-body p-4">
                <div class="mb-3">
                    <label for="fullname">Write your fullname</label>
                    <input 
                    type="text" 
                    name="fullname" 
                    placeholder="Write your fullname" 
                    value="{{contact.fullname}}"
                    class="form-control rounded-0 bg-dark border-0 text-white">
                </div>
        
                <div class="mb-3">
                    <label for="email">Write your email</label>
                    <input 
                    type="text" 
                    name="email" 
                    placeholder="Write your email" 
                    value="{{contact.email}}"
                    class="form-control rounded-0 bg-dark border-0 text-white">
                </div>
        
                <div class="mb-3">
                    <label for="phone">Write your email</label>
                    <input 
                    type="phone" 
                    name="phone" 
                    placeholder="Write your phone" 
                    value="{{contact.phone}}"
                    class="form-control rounded-0 bg-dark border-0 text-white">
                </div>
        
                <div class="d-grid gap-2">
                    <button class="btn btn-secondary">Save</button>
                </div>
            </div>
    
        </form>
    </div>

</div>


{% endblock %}